import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // New in eslint-config-next 16. Flags existing "reset on route change"
    // effects that work correctly; kept visible as warnings to refactor later.
    rules: { "react-hooks/set-state-in-effect": "warn" },
  },
  globalIgnores([
    ".next/**",
    ".open-next/**",
    ".wrangler/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "cloudflare-env.d.ts",
    "desing-inspiration/**",
    // Generated by Payload.
    "src/payload-types.ts",
    "src/migrations/**",
    "src/app/(payload)/**",
  ]),
]);

export default eslintConfig;
